# test
name: version, tag and github release

on:
  push:
    branches: [main]
    paths:
      - 'packages/cli/**'
      - '.github/workflows/**'

defaults:
  run:
    working-directory: packages/cli

jobs:
  release:
    uses: oclif/github-workflows/.github/workflows/githubRelease.yml@main
    with:
      working-directory: packages/cli
    secrets: inherit

  # most repos won't use this
  # depends on previous job to avoid git collisions, not for any functionality reason
  # docs:
  #   uses: salesforcecli/github-workflows/.github/workflows/publishTypedoc.yml@main
  #   secrets: inherit
  #   needs: release
