name: tests
on:
  push:
    branches-ignore: [main]
    paths:
      - 'packages/cli/**'
      - '.github/workflows/**'
  workflow_dispatch:

defaults:
  run:
    working-directory: packages/cli

jobs:
  unit-tests:
    uses: oclif/github-workflows/.github/workflows/unitTest.yml@main
    with:
      working-directory: packages/cli
